version: '3.4'


services:
  jupyter_notebook:
    build:
      context: .
      dockerfile: Dockerfile
    image: notebook:test
    container_name: py3_jn
    
    env_file:
      - ./notebook.env
    
    user: root
    privileged: true
    
    network_mode: "bridge"
    ports:
      - "10888:8888"

    volumes:
      - $PWD/workspace:/home/jovyan

    deploy:
      restart_policy:
        condition: on-failure