version: '3.4'


services:
  redis5:
    container_name: redis5

    image: redis:latest

    network_mode: "bridge"
    
    ports:
      - "6379:6379"

    volumes:
      - $PWD/conf/redis.conf:/etc/redis.conf
      - $PWD/data:/data

    command: redis-server /etc/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master

    deploy:
      restart_policy:
        condition: on-failure